language: python
env:
  - TEST_DB=postgresql://test:testpassword@localhost/test_db
python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before script:
  - psql -c 'CREATE DATABASE test_db;' -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'testpassword';" -U postgres",
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE test_db TO test;'",

# command to run tests
script:
  - coverage run -m pytest -v
  
after_success:
  - coveralls
