language: python
env:
  - TEST_DB=postgresql://postgres@localhost/test_db
python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE test_db;' -U postgres

# command to run tests
script:
  - coverage run -m pytest -v
  
after_success:
  - coveralls
