language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before script:
  - export TEST_DB=postgresql://localhost/test_db
  - psql -c 'CREATE DATABASE test_db;' -U postgres

# command to run tests
script:
  - coverage run -m pytest -v
  
after_success:
  - coveralls
  
  export TEST_DB=postgresql://localhost/test_db
