language: python
env:
  - TEST_DB=postgresql://gray:graycadeau@localhost/stackoverflow_lite
python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before script:
  - psql -c 'CREATE DATABASE stackoverflow_lite;' -U postgres
  - psql -c "CREATE USER gray WITH PASSWORD 'graycadeau';" -U postgres",
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE stackoverflow_lite TO gray;'",

# command to run tests
script:
  - coverage run -m pytest -v
  
after_success:
  - coveralls
