language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before script:
  - psql -c "create role gray with superuser login password 'graycadeau';" -U postgres
  - psql -c 'create database stackoverflow_lite;' -U postgres
  - psql -c 'alter database stackoverflow_lite owner to gray' -U postgres

# command to run tests
script:
  - coverage run -m pytest -v
  
after_success:
  - coveralls
  