language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before script:
  - psql -c 'create database stackoverflow_lite;' -U postgres
  - psql -c "CREATE USER gray WITH PASSWORD 'graycadeau';" -U postgres
  - psql -c 'grant all privileges on database stackoverflow_lite to gray;'

# command to run tests
script:
  - pytest --cov-report term-missing --cov=./
  
after_success:
  - coveralls
  