language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before script:
  - psql -c 'create database stackoverflow_lite;' -U postgres
  - psql -c "CREATE USER gray WITH PASSWORD 'graycadeau';" -U postgres
  - psql -c 'grant all privileges on database stackoverflow_lite to gray;'
  - export FLASK_CONFIG='testing'
  - export FLASK_ENV=development
  - export FLASK_APP=server.py


# command to run tests
script:
  - coverage run -m pytest -v
  
after_success:
  - coveralls
  